//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ingeniux.Runtime.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ingeniux.Runtime.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to asset is forbidden.
        /// </summary>
        internal static string AccessToAssetIsForbidden {
            get {
                return ResourceManager.GetString("AccessToAssetIsForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to asset is not authorized.
        /// </summary>
        internal static string AccessToAssetIsNotAuthorized {
            get {
                return ResourceManager.GetString("AccessToAssetIsNotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to Dynamic Site Server meta data is forbidden..
        /// </summary>
        internal static string AccessToDynamicSiteServerMetaDataIsForbidd {
            get {
                return ResourceManager.GetString("AccessToDynamicSiteServerMetaDataIsForbidd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset doesn&apos;t exist.
        /// </summary>
        internal static string AssetDoesnTExist {
            get {
                return ResourceManager.GetString("AssetDoesnTExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot locate Ingeniux CMS Page.
        /// </summary>
        internal static string CannotLocateIngeniuxCMSPage {
            get {
                return ResourceManager.GetString("CannotLocateIngeniuxCMSPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page requested does not exist.
        /// </summary>
        internal static string Error404BodyCopy {
            get {
                return ResourceManager.GetString("Error404BodyCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Not Found.
        /// </summary>
        internal static string Error404Title {
            get {
                return ResourceManager.GetString("Error404Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Partial View Name &quot;{0}&quot;.
        /// </summary>
        internal static string InvalidPartialViewNameX0 {
            get {
                return ResourceManager.GetString("InvalidPartialViewNameX0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Session Exists for token {0}.
        /// </summary>
        internal static string NoSessionExistsForTokenX0 {
            get {
                return ResourceManager.GetString("NoSessionExistsForTokenX0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap play {
            get {
                object obj = ResourceManager.GetObject("play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Type not recognized.
        /// </summary>
        internal static string RequestTypeNotRecognized {
            get {
                return ResourceManager.GetString("RequestTypeNotRecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not from the authorized pool of IP addresses. Access Denied.
        /// </summary>
        internal static string YouAreNotFromTheAuthorizedPoolOfIPAddresse {
            get {
                return ResourceManager.GetString("YouAreNotFromTheAuthorizedPoolOfIPAddresse", resourceCulture);
            }
        }
    }
}
